# ETL

In [2]:
# imports necesarios
import os
import pandas as pd

In [3]:
# definimos el directorio de trabajo
os.chdir(r'C:\PROYECTOS\SQL\homicidios')
os.getcwd()

'C:\\PROYECTOS\\SQL\\homicidios'

In [4]:
df = pd.read_csv('SAT-HD-BU.csv', sep=";")

C:\Users\germa\AppData\Local\Temp\ipykernel_5520\640119582.py:1: DtypeWarning: Columns (11,21,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('SAT-HD-BU.csv', sep=";")

In [5]:
df.head()

,id_hecho,tipo_hecho_segun_victima,tipo_persona_id,tipo_persona,cant_inc,cant_vic,federal,provincia_id,provincia_nombre,departamento_id,...,victi_situacion_ocupacional_otro,victima_relacion_inculpado,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_años_o_mas,inculpado_clase,inculpado_otro_clase,inculpado_relacion_victima
0,11535,HD Varón,Víctima idRegistro 12235,Víctima,3,1,No,58,Neuquén,58035,...,NaN,Sin relación,No corresponde,No corresponde,-------,No corresponde,No corresponde,No corresponde,----,No corresponde
1,11535,HD Varón,Imputado idRegistro 12929,Imputado,3,1,No,58,Neuquén,58035,...,---------,No corresponde,Masculino,Varón,NaN,Sin determinar,Sin determinar,Sin determinación,NaN,Sin relación
2,11535,HD Varón,Imputado idRegistro 12931,Imputado,3,1,No,58,Neuquén,58035,...,---------,No corresponde,Masculino,Varón,NaN,Sin determinar,Sin determinar,Sin determinación,NaN,Sin relación
3,11535,HD Varón,Imputado idRegistro 12930,Imputado,3,1,No,58,Neuquén,58035,...,---------,No corresponde,Masculino,Varón,NaN,Sin determinar,Sin determinar,Sin determinación,NaN,Sin relación
4,11536,HD Varón,Imputado idRegistro 12933,Imputado,2,1,No,58,Neuquén,58035,...,---------,No corresponde,Masculino,Varón,NaN,20-24,Sí,Civil,NaN,Sin relación

## Conocer información básica

In [6]:
print('Cantidad de filas y columnas', df.shape)
print('Nombre columnas', df.columns)

Cantidad de filas y columnas (38126, 47)
Nombre columnas Index(['id_hecho', 'tipo_hecho_segun_victima', 'tipo_persona_id',
       'tipo_persona', 'cant_inc', 'cant_vic', 'federal', 'provincia_id',
       'provincia_nombre', 'departamento_id', 'departamento_nombre',
       'localidad_id', 'localidad_nombre', 'radio_censal', 'latitud_radio',
       'longitud_radio', 'anio', 'mes', 'fecha_hecho', 'hora_hecho',
       'tipo_lugar', 'tipo_lugar_otro', 'tipo_lugar_ampliado', 'clase_arma',
       'clase_arma_otro', 'en_ocasion_otro_delito',
       'en_ocasion_otro_delito_otro', 'motivo_origen_registro',
       'motivo_origen_registro_otro', 'victima_sexo',
       'victima_identidad_genero', 'victima_identidad_genero_otro',
       'victima_tr_edad', 'victima_18_años_o_mas', 'victima_clase',
       'victima_clase_otro', 'victima_situacion_ocupacional',
       'victi_situacion_ocupacional_otro', 'victima_relacion_inculpado',
       'inculpado_sexo', 'inculpado_identidad_genero',
       'inculpado_identidad_genero_otro', 'inculpado_tr_edad',
       'inculpado_18_años_o_mas', 'inculpado_clase', 'inculpado_otro_clase',
       'inculpado_relacion_victima'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38126 entries, 0 to 38125
Data columns (total 47 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id_hecho                          38126 non-null  int64
 1   tipo_hecho_segun_victima          38126 non-null  object
 2   tipo_persona_id                   38126 non-null  object
 3   tipo_persona                      38126 non-null  object
 4   cant_inc                          38126 non-null  int64
 5   cant_vic                          38126 non-null  int64
 6   federal                           38126 non-null  object
 7   provincia_id                      38126 non-null  int64
 8   provincia_nombre                  38126 non-null  object
 9   departamento_id                   38126 non-null  int64
 10  departamento_nombre               38126 non-null  object
 11  localidad_id                      38120 non-null  object
 12  localidad_nombre                  38126 non-null  object
 13  radio_censal                      32814 non-null  float64
 14  latitud_radio                     32814 non-null  float64
 15  longitud_radio                    32814 non-null  float64
 16  anio                              38126 non-null  int64
 17  mes                               38126 non-null  int64
 18  fecha_hecho                       38126 non-null  object
 19  hora_hecho                        38126 non-null  object
 20  tipo_lugar                        38126 non-null  object
 21  tipo_lugar_otro                   200 non-null    object
 22  tipo_lugar_ampliado               38126 non-null  object
 23  clase_arma                        38126 non-null  object
 24  clase_arma_otro                   427 non-null    object
 25  en_ocasion_otro_delito            38126 non-null  object
 26  en_ocasion_otro_delito_otro       1831 non-null   object
 27  motivo_origen_registro            38126 non-null  object
 28  motivo_origen_registro_otro       137 non-null    object
 29  victima_sexo                      38126 non-null  object
 30  victima_identidad_genero          38126 non-null  object
 31  victima_identidad_genero_otro     20801 non-null  object
 32  victima_tr_edad                   38126 non-null  object
 33  victima_18_años_o_mas             38126 non-null  object
 34  victima_clase                     38126 non-null  object
 35  victima_clase_otro                20866 non-null  object
 36  victima_situacion_ocupacional     38126 non-null  object
 37  victi_situacion_ocupacional_otro  21242 non-null  object
 38  victima_relacion_inculpado        38126 non-null  object
 39  inculpado_sexo                    38126 non-null  object
 40  inculpado_identidad_genero        38126 non-null  object
 41  inculpado_identidad_genero_otro   13476 non-null  object
 42  inculpado_tr_edad                 38126 non-null  object
 43  inculpado_18_años_o_mas           38126 non-null  object
 44  inculpado_clase                   38126 non-null  object
 45  inculpado_otro_clase              17660 non-null  object
 46  inculpado_relacion_victima        38126 non-null  object
dtypes: float64(3), int64(7), object(37)
memory usage: 13.7+ MB

## Seleccionar solo las variables que voy a utilizar

In [8]:
# selecciona columnas que se van a usar para el análisis
# Selecciona las columnas por su nombre, incluyendo las que faltaban
columnas = [
    'id_hecho',
    'provincia_id', 
    'provincia_nombre', 
    'localidad_id', 
    'localidad_nombre', 
    'anio', 
    'mes', 
    'fecha_hecho', 
    'hora_hecho', 
    'tipo_lugar', 
    'tipo_lugar_otro', 
    'tipo_lugar_ampliado', 
    'motivo_origen_registro', 
    'motivo_origen_registro_otro', 
    'victima_sexo', 
    'victima_identidad_genero', 
    'victima_identidad_genero_otro', 
    'victima_tr_edad', 
    'victima_18_años_o_mas', 
    'inculpado_sexo', 
    'inculpado_identidad_genero', 
    'inculpado_identidad_genero_otro',
    'inculpado_tr_edad',
    'inculpado_18_años_o_mas'
]

df_nuevo = df[columnas]

In [9]:
df_nuevo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38126 entries, 0 to 38125
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id_hecho                         38126 non-null  int64
 1   provincia_id                     38126 non-null  int64
 2   provincia_nombre                 38126 non-null  object
 3   localidad_id                     38120 non-null  object
 4   localidad_nombre                 38126 non-null  object
 5   anio                             38126 non-null  int64
 6   mes                              38126 non-null  int64
 7   fecha_hecho                      38126 non-null  object
 8   hora_hecho                       38126 non-null  object
 9   tipo_lugar                       38126 non-null  object
 10  tipo_lugar_otro                  200 non-null    object
 11  tipo_lugar_ampliado              38126 non-null  object
 12  motivo_origen_registro           38126 non-null  object
 13  motivo_origen_registro_otro      137 non-null    object
 14  victima_sexo                     38126 non-null  object
 15  victima_identidad_genero         38126 non-null  object
 16  victima_identidad_genero_otro    20801 non-null  object
 17  victima_tr_edad                  38126 non-null  object
 18  victima_18_años_o_mas            38126 non-null  object
 19  inculpado_sexo                   38126 non-null  object
 20  inculpado_identidad_genero       38126 non-null  object
 21  inculpado_identidad_genero_otro  13476 non-null  object
 22  inculpado_tr_edad                38126 non-null  object
 23  inculpado_18_años_o_mas          38126 non-null  object
dtypes: int64(4), object(20)
memory usage: 7.0+ MB

## Limpieza

In [10]:
df_nuevo.dtypes

id_hecho                            int64
provincia_id                        int64
provincia_nombre                   object
localidad_id                       object
localidad_nombre                   object
anio                                int64
mes                                 int64
fecha_hecho                        object
hora_hecho                         object
tipo_lugar                         object
tipo_lugar_otro                    object
tipo_lugar_ampliado                object
motivo_origen_registro             object
motivo_origen_registro_otro        object
victima_sexo                       object
victima_identidad_genero           object
victima_identidad_genero_otro      object
victima_tr_edad                    object
victima_18_años_o_mas              object
inculpado_sexo                     object
inculpado_identidad_genero         object
inculpado_identidad_genero_otro    object
inculpado_tr_edad                  object
inculpado_18_años_o_mas            object
dtype: object

### Corregir el formato de hora y fecha

In [11]:
# Convertir a datatime (errors='coerse' convierte errores en nulos)
df_nuevo = df_nuevo.copy()
df_nuevo['fecha_hecho'] = pd.to_datetime(df_nuevo['fecha_hecho'], format='%d/%m/%Y', errors='coerce')
df_nuevo['hora_hecho'] = pd.to_datetime(df_nuevo['hora_hecho'],format='%H:%M:%S', errors='coerce').dt.time

### Detectar NaN

In [189]:
# buscar nulos
df_nuevo.isnull().sum()

provincia_id                           0
provincia_nombre                       0
localidad_id                           6
localidad_nombre                       0
anio                                   0
mes                                    0
fecha_hecho                            0
hora_hecho                             0
tipo_lugar                             0
tipo_lugar_otro                    37926
tipo_lugar_ampliado                    0
motivo_origen_registro                 0
motivo_origen_registro_otro        37989
victima_sexo                           0
victima_identidad_genero               0
victima_identidad_genero_otro      17325
victima_tr_edad                        0
victima_18_años_o_mas                  0
inculpado_sexo                         0
inculpado_identidad_genero             0
inculpado_identidad_genero_otro    24650
dtype: int64

In [12]:
# tratar valores nulos y rellenar con texto
df_nuevo = df_nuevo.dropna(subset=['localidad_id']) # no es relevante la cantidad de NaN
df_nuevo['tipo_lugar_otro'] = df_nuevo['tipo_lugar_otro'].fillna('No especificado')
df_nuevo['motivo_origen_registro_otro'] = df_nuevo['motivo_origen_registro_otro'].fillna('No especificado')
df_nuevo['victima_identidad_genero_otro'] = df_nuevo['victima_identidad_genero_otro'].fillna('No especificado')
df_nuevo['inculpado_identidad_genero_otro'] = df_nuevo['inculpado_identidad_genero_otro'].fillna('No especificado')

###  Limpiar y estandarizar textos

In [13]:
# detectar errores de escritura, categorías y desbalances
for col in df_nuevo.select_dtypes(include='object').columns:
    print(df_nuevo[col].value_counts(dropna=False))

provincia_nombre
Buenos Aires                       15673
Santa Fe                            5538
Tucumán                             1959
Ciudad Autónoma de Buenos Aires     1878
Córdoba                             1815
Mendoza                             1563
Chaco                               1379
Salta                               1322
Misiones                             972
Entre Ríos                           878
Chubut                               652
Corrientes                           648
Santiago del Estero                  642
Neuquén                              591
Formosa                              552
Río Negro                            457
Jujuy                                398
San Juan                             271
San Luis                             241
Santa Cruz                           227
Catamarca                            158
La Rioja                             134
La Pampa                             113
Tierra del Fuego                      59
Name: count, dtype: int64
localidad_id
10       10901
10        7454
270       1641
30        1429
20        1201
         ...
350          2
380          2
550.0        2
460.0        2
480.0        2
Name: count, Length: 107, dtype: int64
localidad_nombre
Rosario                                 2716
La Matanza                              2496
Ciudad de Buenos Aires                  1874
San Miguel de Tucumán (Est. Tucumán)    1155
Santa Fe                                1077
                                        ...
Sin determinar                             2
El Arañado                                 2
San Agustín                                2
Villa Mazán                                2
Luque                                      2
Name: count, Length: 1097, dtype: int64
hora_hecho
11:11:11    15413
11:11:00      878
00:00:00      605
22:00:00      454
21:00:00      423
            ...
07:58:00        2
07:02:00        2
12:17:00        2
05:34:00        2
09:59:00        2
Name: count, Length: 1100, dtype: int64
tipo_lugar
Vía pública             20587
Domicilio particular    11102
Sin determinar           3180
Otro lugar               1475
Comercio                  839
Interior de rodados       597
Cárcel o comisaría        340
Name: count, dtype: int64
tipo_lugar_otro
No especificado                                     37920
Descampado                                             45
Zona rural                                             14
Basural                                                14
Establecimiento rural                                   9
Campo                                                   9
Finca                                                   9
Zanja                                                   6
Boliche                                                 5
Cancha                                                  5
Hogar de rehabilitación de adicciones                   5
Río                                                     4
Galpón                                                  4
Monte                                                   4
Carpinteria                                             4
Puente del arroyo el falso                              3
Paraje                                                  3
Establecimiento en costa del lepá                       3
Establecimiento zona rural                              3
Evento privado                                          3
Fabrica                                                 2
Motel                                                   2
Campo ganadero                                          2
Camping                                                 2
Obra en construcción                                    2
Terreno baldio                                          2
Horno de ladrillo                                       2
Quincho                                                 2
Hospital                                                2
Bar                                                     2
Establecimiento Fuerzas de Seguridad / Militares        2
Cochera                                                 2
Paso fronterizo                                         2
Edificación                                             2
Techo de un domicilio vecino                            2
Canal de riego                                          2
Habitación de una empresa                               2
Predio                                                  2
Clinica médica                                          2
Salón de fiesta                                         2
Vías ferreas                                            2
Edificación abandonada                                  2
Arroyo                                                  2
Zona suburbana en las afueras de la ciudad              2
Name: count, dtype: int64
tipo_lugar_ampliado
Vía pública                                            20587
Domicilio particular                                   11102
Sin determinar                                          3180
Comercio                                                 839
Interior de rodados                                      597
Campo/descampado/zona rural                              436
Cárcel o comisaría                                       342
Establecimiento zona rural                               155
Otro lugar                                               123
Río/canal/arroyo/mar/dique                               104
Basural/centro de reciclaje/relleno sanitario             87
Bar/ Boliche/Salón de fiestas/Fiesta                      80
Canchas/club                                              76
Establecimiento de salud                                  73
Hotel/Motel/Hospedaje temporario                          53
Predio                                                    53
Baldío/terreno/lote                                       50
Casa/edificio abandonado /Obra en construcción            48
Barrio de emergencia                                      44
Camping/campamento                                        20
Centro comunitario/centro cultural/asociación civil       16
Bar/Boliche/Salón de fiestas/Fiesta                       14
Establecimiento laboral                                   13
Casa/edificio abandonado/Obra en construcción             12
Geriátrico                                                10
Establecimiento educativo                                  6
Name: count, dtype: int64
motivo_origen_registro
Intervención policial    27811
Denuncia particular       9673
Orden judicial             505
Otros                      131
Name: count, dtype: int64
motivo_origen_registro_otro
No especificado                        37983
Sin determinar                           108
Intervención Servicio Penitenciario       10
Intervención de salud                      7
Cooperacion                                4
Intervención policial                      4
Llamado telefonico                         2
Confesión inculpada                        2
Name: count, dtype: int64
victima_sexo
No corresponde    20798
Masculino         14412
Femenino           2904
Sin determinar        6
Name: count, dtype: int64
victima_identidad_genero
No corresponde          20798
Varón                   14380
Mujer                    2889
Mujer trans/travesti       44
Sin determinar              6
Varón trans                 3
Name: count, dtype: int64
victima_identidad_genero_otro
No especificado    17322
-----------        16079
No corresponde      4719
Name: count, dtype: int64
victima_tr_edad
No corresponde    20798
20-24              2680
25-29              2529
30-34              2350
15-19              1817
35-39              1604
40-44              1321
45-49               958
50-54               726
55-59               603
60-64               474
Sin determinar      472
65-69               409
70-74               324
4 o menos           248
75-79               233
10-14               187
80-84               176
5-9                  89
85-89                82
90 y más             40
Name: count, dtype: int64
victima_18_años_o_mas
No corresponde    20798
Sí                13939
Si                 1665
No                 1391
Sin determinar      327
Name: count, dtype: int64
inculpado_sexo
No corresponde    17322
Masculino         15273
Sin determinar     4180
Femenino           1345
Name: count, dtype: int64
inculpado_identidad_genero
No corresponde          17322
Varón                   15291
Sin determinar           4157
Mujer                    1343
Mujer trans/travesti        6
Varón trans                 1
Name: count, dtype: int64
inculpado_identidad_genero_otro
No especificado    24644
-------            13473
Sin determinar         3
Name: count, dtype: int64
inculpado_tr_edad
No corresponde    17322
Sin determinar     7210
20-24              2758
25-29              2347
30-34              2164
15-19              2110
35-39              1289
40-44               925
45-49               637
50-54               415
55-59               281
60-64               210
65-69               141
10-14               117
70-74               101
75-79                46
80-84                25
90 y más             12
85-89                 9
5-9                   1
Name: count, dtype: int64
inculpado_18_años_o_mas
No corresponde    17322
Sí                12135
Sin determinar     5432
Si                 2154
No                 1077
Name: count, dtype: int64

#### Tratamos 'localidad_id'

In [14]:
# Mostrar los valores únicos de las columnas
df_nuevo['localidad_id'].unique()

array(['100', '40', '70', '10', '30', '130', '50', '220', '20', '200',
       '170', '310', '60', '270', '180', '80', '230', '160', '350', '120',
       '110', '105030', '21010', '35020', '210', '90', '21020', '999',
       '140', '260', '150', '450', '390', '400', '250', '190', '240',
       '360', '112020', '35010', '320', '560', '999-999-2', '280', '370',
       '140020', '999-999-6', '290', '300', '28010', '126070', '340',
       '70020', 170, 180, 310, 140, 270, 80, 230, 20, 160, 200, 60, 10,
       50, 100, 30, 120, 40, 90, 70, 220, 210, 450, 190, 290, 105030, 400,
       110, 560, 440, 130, 280, 340, 150, 370, 360, 154040, 126070, 390,
       300, 240, 21020, 250, 140020, 77020, 126060, 260, 320, 350, 330,
       380, 999, 550.0, 460.0, 480.0], dtype=object)

In [15]:
df_nuevo['localidad_id'].nunique()

107

In [194]:
# Mostrar los valores únicos con su representación exacta
# para ver diferencias entre texto, números, espacios en blanco, etc.
#for x in df_nuevo['localidad_id'].unique():
   # print(repr(x))

In [16]:
# Mostrar las filas donde es igual a, para ver si la info es relevante
print(df_nuevo[df_nuevo['localidad_id'] == '999-999-2'])
print(df_nuevo[df_nuevo['localidad_id'] == '999-999-6'])

       id_hecho  provincia_id                 provincia_nombre localidad_id  \
6515      16185             2  Ciudad Autónoma de Buenos Aires    999-999-2
6516      16185             2  Ciudad Autónoma de Buenos Aires    999-999-2
15934     21996             2  Ciudad Autónoma de Buenos Aires    999-999-2
15935     21996             2  Ciudad Autónoma de Buenos Aires    999-999-2

               localidad_nombre  anio  mes fecha_hecho hora_hecho  \
6515   Localidad sin determinar  2018   11  2018-11-16   21:45:00
6516   Localidad sin determinar  2018   11  2018-11-16   21:45:00
15934  Localidad sin determinar  2020    8  2020-08-15   06:15:00
15935  Localidad sin determinar  2020    8  2020-08-15   06:15:00

        tipo_lugar  ...    victima_sexo victima_identidad_genero  \
6515   Vía pública  ...  No corresponde           No corresponde
6516   Vía pública  ...       Masculino                    Varón
15934  Vía pública  ...  No corresponde           No corresponde
15935  Vía pública  ...       Masculino                    Varón

      victima_identidad_genero_otro victima_tr_edad victima_18_años_o_mas  \
6515                    -----------  No corresponde        No corresponde
6516                No especificado           25-29                    Sí
15934                   -----------  No corresponde        No corresponde
15935               No especificado           15-19                    No

       inculpado_sexo inculpado_identidad_genero  \
6515         Femenino                      Mujer
6516   No corresponde             No corresponde
15934       Masculino                      Varón
15935  No corresponde             No corresponde

      inculpado_identidad_genero_otro inculpado_tr_edad  \
6515                  No especificado             25-29
6516                          -------    No corresponde
15934                 No especificado             20-24
15935                         -------    No corresponde

      inculpado_18_años_o_mas
6515                       Sí
6516           No corresponde
15934                      Sí
15935          No corresponde

[4 rows x 24 columns]
      id_hecho  provincia_id provincia_nombre localidad_id  \
6918     16423             6     Buenos Aires    999-999-6
6919     16423             6     Buenos Aires    999-999-6

              localidad_nombre  anio  mes fecha_hecho hora_hecho  \
6918  Localidad sin determinar  2019    1  2019-01-25   00:30:00
6919  Localidad sin determinar  2019    1  2019-01-25   00:30:00

              tipo_lugar  ...    victima_sexo victima_identidad_genero  \
6918  Cárcel o comisaría  ...  No corresponde           No corresponde
6919  Cárcel o comisaría  ...       Masculino                    Varón

     victima_identidad_genero_otro victima_tr_edad victima_18_años_o_mas  \
6918                   -----------  No corresponde        No corresponde
6919               No especificado           25-29                    Sí

      inculpado_sexo inculpado_identidad_genero  \
6918       Masculino                      Varón
6919  No corresponde             No corresponde

     inculpado_identidad_genero_otro inculpado_tr_edad inculpado_18_años_o_mas
6918                 No especificado    Sin determinar          Sin determinar
6919                         -------    No corresponde          No corresponde

[2 rows x 24 columns]

Se detectaron códigos especiales (999-999-2 y 999-999-6) cuyo contenido en 'localidad_nombre' 
es 'Localidad sin determinar'.
Como el análisis busca mostrar cuáles son las tres provincias y localidades
donde se han detectado la mayor cantidad de homicidios,
se decide reemplazar dichos valores por nulos.

In [17]:
# Reemplazar los códigos de "Localidad sin determinar" por valores nulos (NaN)
df_nuevo['localidad_id'] = df_nuevo['localidad_id'].replace(['999-999-2', '999-999-6'], pd.NA)

In [18]:
# Convertir la columna a tipo numérico (los valores no convertibles quedan como NaN)
df_nuevo['localidad_id'] = pd.to_numeric(df_nuevo['localidad_id'], errors='coerce').astype('Int64')

In [19]:
# Verificar que la conversión se realizó correctamente
df_nuevo['localidad_id'].dtype

Int64Dtype()

In [20]:
df_nuevo['localidad_id'].unique()

<IntegerArray>
[   100,     40,     70,     10,     30,    130,     50,    220,     20,
    200,    170,    310,     60,    270,    180,     80,    230,    160,
    350,    120,    110, 105030,  21010,  35020,    210,     90,  21020,
    999,    140,    260,    150,    450,    390,    400,    250,    190,
    240,    360, 112020,  35010,    320,    560,   <NA>,    280,    370,
 140020,    290,    300,  28010, 126070,    340,  70020,    440, 154040,
  77020, 126060,    330,    380,    550,    460,    480]
Length: 61, dtype: Int64

In [21]:
df_nuevo['localidad_id'].nunique()

60

### Tratamos 'hora_hecho'

In [22]:
df_nuevo['hora_hecho'].value_counts()

hora_hecho
11:11:11    15413
11:11:00      878
00:00:00      605
22:00:00      454
21:00:00      423
            ...
07:58:00        2
07:02:00        2
12:17:00        2
05:34:00        2
09:59:00        2
Name: count, Length: 1100, dtype: int64

In [23]:
from datetime import time
df_nuevo[df_nuevo['hora_hecho'] == time(11,11,11)]

,id_hecho,provincia_id,provincia_nombre,localidad_id,localidad_nombre,anio,mes,fecha_hecho,hora_hecho,tipo_lugar,...,victima_sexo,victima_identidad_genero,victima_identidad_genero_otro,victima_tr_edad,victima_18_años_o_mas,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_años_o_mas
772,12038,82,Santa Fe,270,Rosario,2017,8,2017-08-31,11:11:11,Vía pública,...,No corresponde,No corresponde,-----------,No corresponde,No corresponde,Sin determinar,Sin determinar,No especificado,Sin determinar,Sin determinar
773,12038,82,Santa Fe,270,Rosario,2017,8,2017-08-31,11:11:11,Vía pública,...,Masculino,Varón,No especificado,65-69,Sí,No corresponde,No corresponde,-------,No corresponde,No corresponde
1836,12710,82,Santa Fe,270,Rosario,2018,1,2018-01-28,11:11:11,Domicilio particular,...,No corresponde,No corresponde,-----------,No corresponde,No corresponde,Masculino,Varón,No especificado,35-39,Sí
1837,12710,82,Santa Fe,270,Rosario,2018,1,2018-01-28,11:11:11,Domicilio particular,...,Masculino,Varón,No especificado,85-89,Sí,No corresponde,No corresponde,-------,No corresponde,No corresponde
2221,12955,62,Río Negro,90,Viedma,2017,1,2017-01-01,11:11:11,Vía pública,...,No corresponde,No corresponde,-----------,No corresponde,No corresponde,Masculino,Varón,No especificado,15-19,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38109,37746,6,Buenos Aires,10,Tigre,2024,9,2024-09-28,11:11:11,Vía pública,...,Masculino,Varón,No especificado,30-34,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
38110,37746,6,Buenos Aires,10,Tigre,2024,9,2024-09-28,11:11:11,Vía pública,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Masculino,Varón,No especificado,30-34,Si
38111,37746,6,Buenos Aires,10,Tigre,2024,9,2024-09-28,11:11:11,Vía pública,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Masculino,Varón,No especificado,20-24,Si
38112,37747,6,Buenos Aires,10,Balneario Orense,2024,9,2024-09-04,11:11:11,Vía pública,...,Masculino,Varón,No especificado,25-29,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
38113,37747,6,Buenos Aires,10,Balneario Orense,2024,9,2024-09-04,11:11:11,Vía pública,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Masculino,Varón,No especificado,35-39,Si

In [24]:
df_nuevo[df_nuevo['hora_hecho'] == time(11,11,00)]

,id_hecho,provincia_id,provincia_nombre,localidad_id,localidad_nombre,anio,mes,fecha_hecho,hora_hecho,tipo_lugar,...,victima_sexo,victima_identidad_genero,victima_identidad_genero_otro,victima_tr_edad,victima_18_años_o_mas,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_años_o_mas
29817,30728,58,Neuquén,110,Senillosa,2023,8,2023-08-26,11:11:00,Domicilio particular,...,Masculino,Varón,No especificado,25-29,Sí,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
29818,30728,58,Neuquén,110,Senillosa,2023,8,2023-08-26,11:11:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Masculino,Varón,No especificado,20-24,Sí
30069,30904,82,Santa Fe,270,Rosario,2023,3,2023-03-28,11:11:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Sin determinar,No especificado,Sin determinar,Sí
30070,30904,82,Santa Fe,270,Rosario,2023,3,2023-03-28,11:11:00,Domicilio particular,...,Femenino,Mujer,No especificado,25-29,Sí,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
30305,31052,82,Santa Fe,270,Rosario,2023,7,2023-07-11,11:11:00,Domicilio particular,...,Femenino,Mujer,No especificado,4 o menos,No,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35897,35534,14,Córdoba,10,Córdoba,2024,10,2024-10-05,11:11:00,Otro lugar,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Masculino,Varón,No especificado,45-49,Si
35958,35868,86,Santiago del Estero,110,Santiago del Estero,2024,10,2024-10-18,11:11:00,Domicilio particular,...,Masculino,Varón,No especificado,90 y más,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
35959,35868,86,Santiago del Estero,110,Santiago del Estero,2024,10,2024-10-18,11:11:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Masculino,Varón,No especificado,Sin determinar,Si
36009,35910,2,Ciudad Autónoma de Buenos Aires,10,Ciudad de Buenos Aires,2024,3,2024-03-20,11:11:00,Vía pública,...,Masculino,Varón,No especificado,25-29,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
36010,35910,2,Ciudad Autónoma de Buenos Aires,10,Ciudad de Buenos Aires,2024,3,2024-03-20,11:11:00,Vía pública,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Masculino,Varón,No especificado,30-34,Si

Se conservan los datos con horas '11:11:11' y '11:11:00' ya que representan una gran cantidad de registros necesarios para el análisis. Sin embargo a la hora de analizar la hora del suceso, se procederá a tomar dicha hora dentro de una franja horaria más amplia para evitar el impacto que estos valores puedan tener sobre los resultados.

### Tratamos 'victima_18_años_o_mas'

In [25]:
# ver los valores únicos y las veces que aparecen
df_nuevo['victima_18_años_o_mas'].value_counts(dropna=False)

victima_18_años_o_mas
No corresponde    20798
Sí                13939
Si                 1665
No                 1391
Sin determinar      327
Name: count, dtype: int64

In [26]:
# renombramos la columna
df_nuevo = df_nuevo.rename(columns={'victima_18_años_o_mas':'victima_18_anios_o_mas'})

In [27]:
# unificamos la categoría 'Si' para evitar duplicados
df_nuevo['victima_18_anios_o_mas'] = df_nuevo['victima_18_anios_o_mas'].replace('Sí','Si')

In [28]:
df_nuevo['victima_18_anios_o_mas'] = df_nuevo['victima_18_anios_o_mas'].replace('No corresponde', 'Sin determinar')

In [29]:
df_nuevo['victima_18_anios_o_mas'].value_counts()

victima_18_anios_o_mas
Sin determinar    21125
Si                15604
No                 1391
Name: count, dtype: int64

### Tratamos 'victima_identidad_genero_otro'

In [30]:
df_nuevo['victima_identidad_genero_otro'].value_counts(dropna=False)

victima_identidad_genero_otro
No especificado    17322
-----------        16079
No corresponde      4719
Name: count, dtype: int64

In [31]:
df_nuevo['victima_identidad_genero_otro'] = df_nuevo['victima_identidad_genero_otro'].replace(
    '-----------','No especificado')

In [32]:
df_nuevo['victima_identidad_genero_otro'].value_counts()

victima_identidad_genero_otro
No especificado    33401
No corresponde      4719
Name: count, dtype: int64

### Tratamos ''inculpado_identidad_genero_otro'

In [33]:
df_nuevo['inculpado_identidad_genero_otro'].value_counts(dropna=False)

inculpado_identidad_genero_otro
No especificado    24644
-------            13473
Sin determinar         3
Name: count, dtype: int64

In [34]:
df_nuevo['inculpado_identidad_genero_otro'] = df_nuevo['inculpado_identidad_genero_otro'].replace(
    '-------','No especificado')
df_nuevo['inculpado_identidad_genero_otro'] = df_nuevo['inculpado_identidad_genero_otro'].replace(
    'Sin determinar','No especificado')

In [35]:
df_nuevo['inculpado_identidad_genero_otro'].value_counts()

inculpado_identidad_genero_otro
No especificado    38120
Name: count, dtype: int64

### Tratamos 'tipo_lugar_ampliado'

In [36]:
df_nuevo['tipo_lugar_ampliado'].value_counts(dropna=False)

tipo_lugar_ampliado
Vía pública                                            20587
Domicilio particular                                   11102
Sin determinar                                          3180
Comercio                                                 839
Interior de rodados                                      597
Campo/descampado/zona rural                              436
Cárcel o comisaría                                       342
Establecimiento zona rural                               155
Otro lugar                                               123
Río/canal/arroyo/mar/dique                               104
Basural/centro de reciclaje/relleno sanitario             87
Bar/ Boliche/Salón de fiestas/Fiesta                      80
Canchas/club                                              76
Establecimiento de salud                                  73
Hotel/Motel/Hospedaje temporario                          53
Predio                                                    53
Baldío/terreno/lote                                       50
Casa/edificio abandonado /Obra en construcción            48
Barrio de emergencia                                      44
Camping/campamento                                        20
Centro comunitario/centro cultural/asociación civil       16
Bar/Boliche/Salón de fiestas/Fiesta                       14
Establecimiento laboral                                   13
Casa/edificio abandonado/Obra en construcción             12
Geriátrico                                                10
Establecimiento educativo                                  6
Name: count, dtype: int64

In [37]:
df_nuevo['tipo_lugar_ampliado'] = df_nuevo['tipo_lugar_ampliado'].replace(
    'Bar/ Boliche/Salón de fiestas/Fiesta','Bar/Boliche/Salón de fiestas/Fiesta')

In [38]:
df_nuevo['tipo_lugar_ampliado'] = df_nuevo['tipo_lugar_ampliado'].replace(
    'Casa/edificio abandonado /Obra en construcción','Casa/edificio abandonado/Obra en construcción')

In [39]:
df_nuevo['tipo_lugar_ampliado'].value_counts()

tipo_lugar_ampliado
Vía pública                                            20587
Domicilio particular                                   11102
Sin determinar                                          3180
Comercio                                                 839
Interior de rodados                                      597
Campo/descampado/zona rural                              436
Cárcel o comisaría                                       342
Establecimiento zona rural                               155
Otro lugar                                               123
Río/canal/arroyo/mar/dique                               104
Bar/Boliche/Salón de fiestas/Fiesta                       94
Basural/centro de reciclaje/relleno sanitario             87
Canchas/club                                              76
Establecimiento de salud                                  73
Casa/edificio abandonado/Obra en construcción             60
Hotel/Motel/Hospedaje temporario                          53
Predio                                                    53
Baldío/terreno/lote                                       50
Barrio de emergencia                                      44
Camping/campamento                                        20
Centro comunitario/centro cultural/asociación civil       16
Establecimiento laboral                                   13
Geriátrico                                                10
Establecimiento educativo                                  6
Name: count, dtype: int64

## Duplicados

In [40]:
# contar cuántos duplicados hay
df_nuevo.duplicated().sum()

np.int64(1591)

In [41]:
# ver cuáles son
df_nuevo[df_nuevo.duplicated(keep=False)].head()

,id_hecho,provincia_id,provincia_nombre,localidad_id,localidad_nombre,anio,mes,fecha_hecho,hora_hecho,tipo_lugar,...,victima_sexo,victima_identidad_genero,victima_identidad_genero_otro,victima_tr_edad,victima_18_anios_o_mas,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_años_o_mas
1,11535,58,Neuquén,100,Plottier,2017,1,2017-01-14,22:38:00,Domicilio particular,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,Sin determinar,Sin determinar
2,11535,58,Neuquén,100,Plottier,2017,1,2017-01-14,22:38:00,Domicilio particular,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,Sin determinar,Sin determinar
3,11535,58,Neuquén,100,Plottier,2017,1,2017-01-14,22:38:00,Domicilio particular,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,Sin determinar,Sin determinar
46,11573,66,Salta,20,Colonia Santa Rosa,2017,1,2017-01-08,06:30:00,Vía pública,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,20-24,Sí
47,11573,66,Salta,20,Colonia Santa Rosa,2017,1,2017-01-08,06:30:00,Vía pública,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,20-24,Sí

In [42]:
df_nuevo[df_nuevo.duplicated(keep=False)].tail()

,id_hecho,provincia_id,provincia_nombre,localidad_id,localidad_nombre,anio,mes,fecha_hecho,hora_hecho,tipo_lugar,...,victima_sexo,victima_identidad_genero,victima_identidad_genero_otro,victima_tr_edad,victima_18_anios_o_mas,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_años_o_mas
38091,37740,6,Buenos Aires,10,Quilmes,2024,9,2024-09-20,11:11:11,Vía pública,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Masculino,Varón,No especificado,15-19,No
38092,37740,6,Buenos Aires,10,Quilmes,2024,9,2024-09-20,11:11:11,Vía pública,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Masculino,Varón,No especificado,15-19,No
38094,37740,6,Buenos Aires,10,Quilmes,2024,9,2024-09-20,11:11:11,Vía pública,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Masculino,Varón,No especificado,15-19,No
38097,37741,6,Buenos Aires,10,Quilmes,2024,9,2024-09-28,11:11:11,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Masculino,Varón,No especificado,15-19,Si
38098,37741,6,Buenos Aires,10,Quilmes,2024,9,2024-09-28,11:11:11,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Masculino,Varón,No especificado,15-19,Si

In [43]:
# eliminamos duplicados
df_nuevo = df_nuevo.drop_duplicates()

In [44]:
# confirmar que no queden duplicados
df_nuevo.duplicated().sum()

np.int64(0)

In [45]:
# ver el tamaño final de tabla
print('Cantidad de filas y columnas', df_nuevo.shape)
print('Nombre columnas', df_nuevo.columns)

Cantidad de filas y columnas (36529, 24)
Nombre columnas Index(['id_hecho', 'provincia_id', 'provincia_nombre', 'localidad_id',
       'localidad_nombre', 'anio', 'mes', 'fecha_hecho', 'hora_hecho',
       'tipo_lugar', 'tipo_lugar_otro', 'tipo_lugar_ampliado',
       'motivo_origen_registro', 'motivo_origen_registro_otro', 'victima_sexo',
       'victima_identidad_genero', 'victima_identidad_genero_otro',
       'victima_tr_edad', 'victima_18_anios_o_mas', 'inculpado_sexo',
       'inculpado_identidad_genero', 'inculpado_identidad_genero_otro',
       'inculpado_tr_edad', 'inculpado_18_años_o_mas'],
      dtype='object')

### Tratamos 'victima_tr_edad'

In [46]:
df_nuevo['victima_tr_edad'].value_counts()

victima_tr_edad
No corresponde    19305
20-24              2661
25-29              2512
30-34              2333
15-19              1801
35-39              1599
40-44              1317
45-49               958
50-54               724
55-59               603
60-64               474
Sin determinar      459
65-69               408
70-74               324
4 o menos           245
75-79               233
10-14               187
80-84               176
5-9                  88
85-89                82
90 y más             40
Name: count, dtype: int64

In [47]:
df_nuevo[df_nuevo['victima_tr_edad'] == 'No corresponde']

,id_hecho,provincia_id,provincia_nombre,localidad_id,localidad_nombre,anio,mes,fecha_hecho,hora_hecho,tipo_lugar,...,victima_sexo,victima_identidad_genero,victima_identidad_genero_otro,victima_tr_edad,victima_18_anios_o_mas,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_años_o_mas
1,11535,58,Neuquén,100,Plottier,2017,1,2017-01-14,22:38:00,Domicilio particular,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,Sin determinar,Sin determinar
4,11536,58,Neuquén,40,Cutral Có,2017,1,2017-01-07,10:35:00,Vía pública,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,20-24,Sí
5,11536,58,Neuquén,40,Cutral Có,2017,1,2017-01-07,10:35:00,Vía pública,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,30-34,Sí
8,11537,58,Neuquén,70,Neuquén,2017,1,2017-01-07,16:38:00,Vía pública,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,25-29,Sí
9,11538,58,Neuquén,10,Barrancas,2017,1,2017-01-02,22:00:00,Domicilio particular,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,35-39,Sí
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38117,37757,62,Río Negro,60,San Carlos de Bariloche,2024,4,2024-04-09,08:00:00,Otro lugar,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Masculino,Varón,No especificado,Sin determinar,Si
38119,37758,62,Río Negro,30,El Bolsón,2024,7,2024-07-13,07:00:00,Vía pública,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Masculino,Varón,No especificado,Sin determinar,Si
38121,37759,62,Río Negro,80,Barrio Chacra Monte,2024,11,2024-11-20,00:43:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Masculino,Varón,No especificado,35-39,Si
38122,37796,82,Santa Fe,170,Santa Fe,2024,3,2024-03-03,19:30:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Masculino,Varón,No especificado,20-24,Si
38124,34739,54,Misiones,10,Esperanza,2023,12,2023-12-29,19:00:00,Interior de rodados,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Sin determinar,Sin determinar,No especificado,Sin determinar,Si

In [48]:
df_nuevo[df_nuevo['victima_tr_edad'] == 'Sin determinar']

,id_hecho,provincia_id,provincia_nombre,localidad_id,localidad_nombre,anio,mes,fecha_hecho,hora_hecho,tipo_lugar,...,victima_sexo,victima_identidad_genero,victima_identidad_genero_otro,victima_tr_edad,victima_18_anios_o_mas,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_años_o_mas
58,11578,66,Salta,70,San Ramón de la Nueva Orán (Est. Orán),2017,1,2017-01-25,01:00:00,Vía pública,...,Masculino,Varón,No especificado,Sin determinar,Sin determinar,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
66,11584,26,Chubut,40,Trelew,2017,2,2017-02-24,19:40:00,Domicilio particular,...,Masculino,Varón,No especificado,Sin determinar,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
400,11779,66,Salta,10,El Galpón (Est. Foguista J. F. Juárez),2017,3,2017-03-17,00:00:00,Vía pública,...,Femenino,Mujer,No especificado,Sin determinar,Sin determinar,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
576,11921,58,Neuquén,10,San Martín de los Andes,2017,8,2017-08-04,23:55:00,Domicilio particular,...,Masculino,Varón,No especificado,Sin determinar,Sin determinar,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
892,12191,82,Santa Fe,30,Las Parejas,2017,10,2017-10-20,05:45:00,Domicilio particular,...,Femenino,Mujer,No especificado,Sin determinar,Sin determinar,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37736,37537,6,Buenos Aires,10,Lomas de Zamora,2024,6,2024-06-15,11:11:11,Vía pública,...,Masculino,Varón,No especificado,Sin determinar,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
37849,37593,6,Buenos Aires,10,La Matanza,2024,8,2024-08-05,11:11:11,Interior de rodados,...,Masculino,Varón,No especificado,Sin determinar,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
37853,37595,6,Buenos Aires,10,La Matanza,2024,8,2024-08-08,11:11:11,Vía pública,...,Masculino,Varón,No especificado,Sin determinar,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
38038,37719,6,Buenos Aires,10,La Matanza,2024,9,2024-09-19,11:11:11,Vía pública,...,Masculino,Varón,No especificado,Sin determinar,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
38067,37731,6,Buenos Aires,10,Malvinas Argentinas,2024,9,2024-09-08,11:11:11,Vía pública,...,Masculino,Varón,No especificado,Sin determinar,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde

In [49]:
df_nuevo['victima_tr_edad'] = df_nuevo['victima_tr_edad'].replace('No corresponde', 'Sin determinar')

In [50]:
df_nuevo['victima_tr_edad'].value_counts()

victima_tr_edad
Sin determinar    19764
20-24              2661
25-29              2512
30-34              2333
15-19              1801
35-39              1599
40-44              1317
45-49               958
50-54               724
55-59               603
60-64               474
65-69               408
70-74               324
4 o menos           245
75-79               233
10-14               187
80-84               176
5-9                  88
85-89                82
90 y más             40
Name: count, dtype: int64

### Tratamos 'inculpado_18_años_o_mas'

In [51]:
# renombramos la columna del inculpado
df_nuevo = df_nuevo.rename(columns={'inculpado_18_años_o_mas':'inculpado_18_anios_o_mas'})

In [52]:
# unificamos la categoría 'Si' y reemplazamos 'No corresponde'
df_nuevo['inculpado_18_anios_o_mas'] = df_nuevo['inculpado_18_anios_o_mas'].replace('Sí', 'Si')
df_nuevo['inculpado_18_anios_o_mas'] = df_nuevo['inculpado_18_anios_o_mas'].replace('No corresponde', 'Sin determinar')

### Tratamos 'inculpado_tr_edad'

In [53]:
# reemplazamos 'No corresponde' en el tramo de edad del inculpado
df_nuevo['inculpado_tr_edad'] = df_nuevo['inculpado_tr_edad'].replace('No corresponde', 'Sin determinar')

In [54]:
df_nuevo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 36529 entries, 0 to 38125
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id_hecho                         36529 non-null  int64
 1   provincia_id                     36529 non-null  int64
 2   provincia_nombre                 36529 non-null  object
 3   localidad_id                     36523 non-null  Int64
 4   localidad_nombre                 36529 non-null  object
 5   anio                             36529 non-null  int64
 6   mes                              36529 non-null  int64
 7   fecha_hecho                      36529 non-null  datetime64[ns]
 8   hora_hecho                       36529 non-null  object
 9   tipo_lugar                       36529 non-null  object
 10  tipo_lugar_otro                  36529 non-null  object
 11  tipo_lugar_ampliado              36529 non-null  object
 12  motivo_origen_registro           36529 non-null  object
 13  motivo_origen_registro_otro      36529 non-null  object
 14  victima_sexo                     36529 non-null  object
 15  victima_identidad_genero         36529 non-null  object
 16  victima_identidad_genero_otro    36529 non-null  object
 17  victima_tr_edad                  36529 non-null  object
 18  victima_18_anios_o_mas           36529 non-null  object
 19  inculpado_sexo                   36529 non-null  object
 20  inculpado_identidad_genero       36529 non-null  object
 21  inculpado_identidad_genero_otro  36529 non-null  object
 22  inculpado_tr_edad                36529 non-null  object
 23  inculpado_18_anios_o_mas         36529 non-null  object
dtypes: Int64(1), datetime64[ns](1), int64(4), object(18)
memory usage: 7.0+ MB

In [57]:
df_nuevo.to_csv('homicidios_limpio.csv', index=False, sep=';', encoding='utf-8')