In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('involucrados.csv')

In [4]:
# Separar Víctimas
df_victimas = df[['id_hecho',
'victima_sexo',
'victima_identidad_genero',
'victima_identidad_genero_otro',
'victima_tr_edad',
'victima_18_anios_o_mas']].copy()

df_victimas.rename(columns={
    'id_hecho': 'hecho_id',
    'victima_sexo': 'sexo',
    'victima_identidad_genero': 'identidad_genero',
    'victima_identidad_genero_otro': 'identidad_genero_otro',
    'victima_tr_edad': 'tr_edad', 
    'victima_18_anios_o_mas': 'mayor_18_anios'
}, inplace=True)

df_victimas['tipo_involucrado'] = 'victima'

In [5]:
df_victimas.head()

,hecho_id,sexo,identidad_genero,identidad_genero_otro,tr_edad,mayor_18_anios,tipo_involucrado
0,11535,Masculino,Varón,No especificado,45-49,Si,victima
1,11535,No corresponde,No corresponde,No especificado,Sin determinar,Sin determinar,victima
2,11536,No corresponde,No corresponde,No especificado,Sin determinar,Sin determinar,victima
3,11536,No corresponde,No corresponde,No especificado,Sin determinar,Sin determinar,victima
4,11536,Masculino,Varón,No especificado,40-44,Si,victima

In [7]:
# Separar Inculpados
df_inculpados = df[['id_hecho',
'inculpado_sexo',
'inculpado_identidad_genero',
'inculpado_identidad_genero_otro',
'inculpado_tr_edad',
'inculpado_18_anios_o_mas']].copy()

df_inculpados.rename(columns={
    'id_hecho': 'hecho_id',
    'inculpado_sexo': 'sexo',
    'inculpado_identidad_genero': 'identidad_genero',
    'inculpado_identidad_genero_otro': 'identidad_genero_otro',
    'inculpado_tr_edad': 'tr_edad', 
    'inculpado_18_anios_o_mas': 'mayor_18_anios'
}, inplace=True)
df_inculpados['tipo_involucrado'] = 'inculpado'

In [8]:
df_inculpados.head()

,hecho_id,sexo,identidad_genero,identidad_genero_otro,tr_edad,mayor_18_anios,tipo_involucrado
0,11535,No corresponde,No corresponde,No especificado,Sin determinar,Sin determinar,inculpado
1,11535,Masculino,Varón,No especificado,Sin determinar,Sin determinar,inculpado
2,11536,Masculino,Varón,No especificado,20-24,Si,inculpado
3,11536,Masculino,Varón,No especificado,30-34,Si,inculpado
4,11536,No corresponde,No corresponde,No especificado,Sin determinar,Sin determinar,inculpado

In [9]:
# Unir ambos DataFrames
df_involucrados_melt = pd.concat([df_victimas, df_inculpados], ignore_index=True)

In [11]:
# Exportar el nuevo CSV
df_involucrados_melt.to_csv('involucrados.csv', index=False, encoding='utf-8')

In [15]:
# Ordenamos las columnas exactamente como las espera SQL
orden_columnas = [
    'tipo_involucrado', 
    'sexo', 
    'identidad_genero', 
    'identidad_genero_otro', 
    'tr_edad', 
    'mayor_18_anios', 
    'hecho_id'
]
df_involucrados_melt = df_involucrados_melt[orden_columnas]

# Exportamos el CSV limpio y ordenado
df_involucrados_melt.to_csv('involucrados.csv', index=False, encoding='utf-8')