# ETL

In [14]:
# imports necesarios
import pandas as pd
import os

In [15]:
print("Directorio de trabajo:", os.getcwd())
print("¿Existe el archivo?:", os.path.exists("../data/SAT-HD-BU.csv"))

Directorio de trabajo: C:\PROYECTOS\SQL\homicidios
¿Existe el archivo?: False

In [16]:
df = pd.read_csv(
    'data/SAT-HD-BU.csv',
    sep=',',
    encoding='utf-8',
    low_memory=False
)

In [17]:
df.head()

,id_hecho,tipo_persona_id,tipo_persona,cant_inc,cant_vic,federal,provincia_id,provincia_nombre,departamento_id,departamento_nombre,...,victi_situacion_ocupacional_otro,victima_relacion_inculpado,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_años_o_mas,inculpado_clase,inculpado_otro_clase,inculpado_relacion_victima
0,11535,Víctima idRegistro 12235,Víctima,3,1,No,58,Neuquén,58035,Confluencia,...,NaN,Sin relación,No corresponde,No corresponde,-------,No corresponde,No corresponde,No corresponde,----,No corresponde
1,11535,Imputado idRegistro 12929,Imputado,3,1,No,58,Neuquén,58035,Confluencia,...,---------,No corresponde,Masculino,Varón,NaN,Sin determinar,Sin determinar,Sin determinación,NaN,Sin relación
2,11535,Imputado idRegistro 12931,Imputado,3,1,No,58,Neuquén,58035,Confluencia,...,---------,No corresponde,Masculino,Varón,NaN,Sin determinar,Sin determinar,Sin determinación,NaN,Sin relación
3,11535,Imputado idRegistro 12930,Imputado,3,1,No,58,Neuquén,58035,Confluencia,...,---------,No corresponde,Masculino,Varón,NaN,Sin determinar,Sin determinar,Sin determinación,NaN,Sin relación
4,11536,Imputado idRegistro 12933,Imputado,2,1,No,58,Neuquén,58035,Confluencia,...,---------,No corresponde,Masculino,Varón,NaN,20-24,Sí,Civil,NaN,Sin relación

## Conocer información básica

In [18]:
print('Cantidad de filas y columnas', df.shape)
print('Nombre columnas', df.columns)

Cantidad de filas y columnas (42051, 46)
Nombre columnas Index(['id_hecho', 'tipo_persona_id', 'tipo_persona', 'cant_inc', 'cant_vic',
       'federal', 'provincia_id', 'provincia_nombre', 'departamento_id',
       'departamento_nombre', 'localidad_id', 'localidad_nombre',
       'radio_censal', 'latitud_radio', 'longitud_radio', 'anio', 'mes',
       'fecha_hecho', 'hora_hecho', 'tipo_lugar', 'tipo_lugar_otro',
       'tipo_lugar_ampliado', 'clase_arma', 'clase_arma_otro',
       'en_ocasion_otro_delito', 'en_ocasion_otro_delito_otro',
       'motivo_origen_registro', 'motivo_origen_registro_otro', 'victima_sexo',
       'victima_identidad_genero', 'victima_identidad_genero_otro',
       'victima_tr_edad', 'victima_18_años_o_mas', 'victima_clase',
       'victima_clase_otro', 'victima_situacion_ocupacional',
       'victi_situacion_ocupacional_otro', 'victima_relacion_inculpado',
       'inculpado_sexo', 'inculpado_identidad_genero',
       'inculpado_identidad_genero_otro', 'inculpado_tr_edad',
       'inculpado_18_años_o_mas', 'inculpado_clase', 'inculpado_otro_clase',
       'inculpado_relacion_victima'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42051 entries, 0 to 42050
Data columns (total 46 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id_hecho                          42051 non-null  int64
 1   tipo_persona_id                   42051 non-null  object
 2   tipo_persona                      42051 non-null  object
 3   cant_inc                          42051 non-null  int64
 4   cant_vic                          42051 non-null  int64
 5   federal                           42051 non-null  object
 6   provincia_id                      42051 non-null  int64
 7   provincia_nombre                  42051 non-null  object
 8   departamento_id                   42051 non-null  int64
 9   departamento_nombre               42051 non-null  object
 10  localidad_id                      42045 non-null  object
 11  localidad_nombre                  42051 non-null  object
 12  radio_censal                      35981 non-null  float64
 13  latitud_radio                     35981 non-null  float64
 14  longitud_radio                    35981 non-null  float64
 15  anio                              42051 non-null  int64
 16  mes                               42051 non-null  int64
 17  fecha_hecho                       42051 non-null  object
 18  hora_hecho                        42051 non-null  object
 19  tipo_lugar                        42051 non-null  object
 20  tipo_lugar_otro                   115 non-null    object
 21  tipo_lugar_ampliado               42051 non-null  object
 22  clase_arma                        42051 non-null  object
 23  clase_arma_otro                   452 non-null    object
 24  en_ocasion_otro_delito            42051 non-null  object
 25  en_ocasion_otro_delito_otro       1986 non-null   object
 26  motivo_origen_registro            42051 non-null  object
 27  motivo_origen_registro_otro       141 non-null    object
 28  victima_sexo                      42051 non-null  object
 29  victima_identidad_genero          42051 non-null  object
 30  victima_identidad_genero_otro     22962 non-null  object
 31  victima_tr_edad                   42051 non-null  object
 32  victima_18_años_o_mas             42051 non-null  object
 33  victima_clase                     42051 non-null  object
 34  victima_clase_otro                23029 non-null  object
 35  victima_situacion_ocupacional     42051 non-null  object
 36  victi_situacion_ocupacional_otro  23448 non-null  object
 37  victima_relacion_inculpado        42051 non-null  object
 38  inculpado_sexo                    42051 non-null  object
 39  inculpado_identidad_genero        41687 non-null  object
 40  inculpado_identidad_genero_otro   13476 non-null  object
 41  inculpado_tr_edad                 42051 non-null  object
 42  inculpado_18_años_o_mas           42051 non-null  object
 43  inculpado_clase                   42051 non-null  object
 44  inculpado_otro_clase              19449 non-null  object
 45  inculpado_relacion_victima        42051 non-null  object
dtypes: float64(3), int64(7), object(36)
memory usage: 14.8+ MB

## Seleccionar solo las variables que voy a utilizar

In [20]:
# selecciona columnas que se van a usar para el análisis
# Selecciona las columnas por su nombre, incluyendo las que faltaban
columnas = [
    'id_hecho',
    'provincia_id', 
    'provincia_nombre', 
    'localidad_id', 
    'localidad_nombre', 
    'anio', 
    'mes', 
    'fecha_hecho', 
    'hora_hecho', 
    'tipo_lugar', 
    'tipo_lugar_otro', 
    'tipo_lugar_ampliado', 
    'motivo_origen_registro', 
    'motivo_origen_registro_otro', 
    'victima_sexo', 
    'victima_identidad_genero', 
    'victima_identidad_genero_otro', 
    'victima_tr_edad', 
    'victima_18_años_o_mas', 
    'inculpado_sexo', 
    'inculpado_identidad_genero', 
    'inculpado_identidad_genero_otro',
    'inculpado_tr_edad',
    'inculpado_18_años_o_mas'
]

df_nuevo = df[columnas]

In [21]:
df_nuevo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42051 entries, 0 to 42050
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id_hecho                         42051 non-null  int64
 1   provincia_id                     42051 non-null  int64
 2   provincia_nombre                 42051 non-null  object
 3   localidad_id                     42045 non-null  object
 4   localidad_nombre                 42051 non-null  object
 5   anio                             42051 non-null  int64
 6   mes                              42051 non-null  int64
 7   fecha_hecho                      42051 non-null  object
 8   hora_hecho                       42051 non-null  object
 9   tipo_lugar                       42051 non-null  object
 10  tipo_lugar_otro                  115 non-null    object
 11  tipo_lugar_ampliado              42051 non-null  object
 12  motivo_origen_registro           42051 non-null  object
 13  motivo_origen_registro_otro      141 non-null    object
 14  victima_sexo                     42051 non-null  object
 15  victima_identidad_genero         42051 non-null  object
 16  victima_identidad_genero_otro    22962 non-null  object
 17  victima_tr_edad                  42051 non-null  object
 18  victima_18_años_o_mas            42051 non-null  object
 19  inculpado_sexo                   42051 non-null  object
 20  inculpado_identidad_genero       41687 non-null  object
 21  inculpado_identidad_genero_otro  13476 non-null  object
 22  inculpado_tr_edad                42051 non-null  object
 23  inculpado_18_años_o_mas          42051 non-null  object
dtypes: int64(4), object(20)
memory usage: 7.7+ MB

## Limpieza

In [22]:
df_nuevo.dtypes

id_hecho                            int64
provincia_id                        int64
provincia_nombre                   object
localidad_id                       object
localidad_nombre                   object
anio                                int64
mes                                 int64
fecha_hecho                        object
hora_hecho                         object
tipo_lugar                         object
tipo_lugar_otro                    object
tipo_lugar_ampliado                object
motivo_origen_registro             object
motivo_origen_registro_otro        object
victima_sexo                       object
victima_identidad_genero           object
victima_identidad_genero_otro      object
victima_tr_edad                    object
victima_18_años_o_mas              object
inculpado_sexo                     object
inculpado_identidad_genero         object
inculpado_identidad_genero_otro    object
inculpado_tr_edad                  object
inculpado_18_años_o_mas            object
dtype: object

### Corregir el formato de hora y fecha

In [23]:
# Convertir a datatime (errors='coerse' convierte errores en nulos)
df_nuevo = df_nuevo.copy()
df_nuevo['fecha_hecho'] = pd.to_datetime(df_nuevo['fecha_hecho'], format='%d/%m/%Y', errors='coerce')
df_nuevo['hora_hecho'] = pd.to_datetime(df_nuevo['hora_hecho'],format='%H:%M:%S', errors='coerce').dt.time

### Detectar NaN

In [24]:
# buscar nulos
df_nuevo.isnull().sum()

id_hecho                               0
provincia_id                           0
provincia_nombre                       0
localidad_id                           6
localidad_nombre                       0
anio                                   0
mes                                    0
fecha_hecho                            0
hora_hecho                             0
tipo_lugar                             0
tipo_lugar_otro                    41936
tipo_lugar_ampliado                    0
motivo_origen_registro                 0
motivo_origen_registro_otro        41910
victima_sexo                           0
victima_identidad_genero               0
victima_identidad_genero_otro      19089
victima_tr_edad                        0
victima_18_años_o_mas                  0
inculpado_sexo                         0
inculpado_identidad_genero           364
inculpado_identidad_genero_otro    28575
inculpado_tr_edad                      0
inculpado_18_años_o_mas                0
dtype: int64

In [25]:
# tratar valores nulos y rellenar con texto
df_nuevo = df_nuevo.dropna(subset=['localidad_id']) # no es relevante la cantidad de NaN
df_nuevo['tipo_lugar_otro'] = df_nuevo['tipo_lugar_otro'].fillna('No especificado')
df_nuevo['motivo_origen_registro_otro'] = df_nuevo['motivo_origen_registro_otro'].fillna('No especificado')
df_nuevo['victima_identidad_genero_otro'] = df_nuevo['victima_identidad_genero_otro'].fillna('No especificado')
df_nuevo['inculpado_identidad_genero_otro'] = df_nuevo['inculpado_identidad_genero_otro'].fillna('No especificado')

###  Limpiar y estandarizar textos

In [26]:
# detectar errores de escritura, categorías y desbalances
for col in df_nuevo.select_dtypes(include='object').columns:
    print(df_nuevo[col].value_counts(dropna=False))

provincia_nombre
Buenos Aires                       17505
Santa Fe                            5965
Ciudad Autónoma de Buenos Aires     2196
Tucumán                             2070
Córdoba                             2007
Mendoza                             1716
Chaco                               1498
Salta                               1429
Misiones                            1079
Entre Ríos                           955
Chubut                               698
Santiago del Estero                  684
Neuquén                              677
Corrientes                           674
Formosa                              591
Río Negro                            507
Jujuy                                464
San Juan                             295
Santa Cruz                           258
San Luis                             256
Catamarca                            170
La Rioja                             158
La Pampa                             125
Tierra del Fuego                      68
Name: count, dtype: int64
localidad_id
10     20519
270     2921
30      2711
20      2404
50      1972
       ...
330        2
380        2
550        2
460        2
480        2
Name: count, Length: 62, dtype: int64
localidad_nombre
Rosario                                 2902
La Matanza                              2855
Ciudad de Buenos Aires                  2192
San Miguel de Tucumán (Est. Tucumán)    1225
Santa Fe                                1150
                                        ...
San Clemente del Tuyú                      2
La Colonia                                 2
Dina Huapi                                 2
Casa de Piedra                             2
Cervantes                                  2
Name: count, Length: 1133, dtype: int64
hora_hecho
11:11:11    15413
11:11:00      919
00:00:00      665
22:00:00      526
21:00:00      497
            ...
19:09:00        2
09:07:00        2
15:43:00        2
06:19:00        2
16:38:00        2
Name: count, Length: 1152, dtype: int64
tipo_lugar
Vía pública             23139
Domicilio particular    12222
Sin determinar           3207
Otro lugar               1590
Comercio                  909
Interior de rodados       607
Cárcel o comisaría        371
Name: count, dtype: int64
tipo_lugar_otro
No especificado              41930
Zona rural                      12
Río                             12
Hotel                           10
Establecimiento público         10
Finca                            6
Cancha                           6
Obra en construcción             5
Descampado                       4
Campo                            4
Canal                            4
Zona boscosa                     3
Trillo                           3
Descampado zona subrubana        2
Basural                          2
Terreno descampado               2
Descampado zona rural            2
Mercado                          2
Edificación abandonada           2
Baldío/terreno/lote              2
Hospital                         2
Monte                            2
Establecimiento rural            2
Baldio                           2
Construccion precaria            2
Estadio deportivo                2
Centro médico                    2
Iglesia                          2
Complejo de edificios            2
Plaza/parque                     2
Otros                            2
Name: count, dtype: int64
tipo_lugar_ampliado
Vía pública                                            23139
Domicilio particular                                   12222
Sin determinar                                          3207
Comercio                                                 909
Interior de rodados                                      607
Campo/descampado/zona rural                              467
Cárcel o comisaría                                       373
Establecimiento zona rural                               163
Otro lugar                                               146
Río/canal/arroyo/mar/dique                               120
Basural/centro de reciclaje/relleno sanitario             89
Canchas/club                                              84
Bar/ Boliche/Salón de fiestas/Fiesta                      80
Establecimiento de salud                                  77
Hotel/Motel/Hospedaje temporario                          63
Casa/edificio abandonado /Obra en construcción            55
Baldío/terreno/lote                                       54
Predio                                                    53
Barrio de emergencia                                      44
Camping/campamento                                        20
Centro comunitario/centro cultural/asociación civil       16
Bar/Boliche/Salón de fiestas/Fiesta                       14
Establecimiento laboral                                   13
Casa/edificio abandonado/Obra en construcción             12
Geriátrico                                                10
Establecimiento educativo                                  6
Otro                                                       2
Name: count, dtype: int64
motivo_origen_registro
Intervención policial                  30972
Denuncia particular                    10403
Orden judicial                           533
Otros                                    135
Intervención Servicio Penitenciario        2
Name: count, dtype: int64
motivo_origen_registro_otro
No especificado                        41904
Sin determinar                           108
Intervención Servicio Penitenciario       10
Intervención de salud                      7
Intervención policial                      4
Cooperacion                                4
Confesión inculpada                        2
Llamado telefonico                         2
Bomberos                                   2
Servicios de salud                         2
Name: count, dtype: int64
victima_sexo
No corresponde    22959
Masculino         15879
Femenino           3200
Sin determinar        7
Name: count, dtype: int64
victima_identidad_genero
No corresponde          22959
Varón                   15842
Mujer                    3185
Mujer trans/travesti       49
Sin determinar              7
Varón trans                 3
Name: count, dtype: int64
victima_identidad_genero_otro
No especificado    19086
-----------        16079
No corresponde      6880
Name: count, dtype: int64
victima_tr_edad
No corresponde    22959
20-24              2908
25-29              2776
30-34              2580
15-19              1980
35-39              1804
40-44              1473
45-49              1089
50-54               795
55-59               661
Sin determinar      527
60-64               522
65-69               455
70-74               361
4 o menos           263
75-79               259
10-14               203
80-84               194
5-9                  99
85-89                92
90 y más             45
Name: count, dtype: int64
victima_18_años_o_mas
No corresponde    22959
Sí                13939
Si                 3300
No                 1520
Sin determinar      327
Name: count, dtype: int64
inculpado_sexo
No corresponde    19086
Masculino         16892
Sin determinar     4543
Femenino           1524
Name: count, dtype: int64
inculpado_identidad_genero
No corresponde          19086
Varón                   16906
Sin determinar           4157
Mujer                    1522
NaN                       364
Mujer trans/travesti        8
Varón trans                 1
Otro (Especificar)          1
Name: count, dtype: int64
inculpado_identidad_genero_otro
No especificado    28569
-------            13473
Sin determinar         3
Name: count, dtype: int64
inculpado_tr_edad
No corresponde    19086
Sin determinar     7872
20-24              2980
25-29              2603
30-34              2387
15-19              2331
35-39              1464
40-44              1047
45-49               729
50-54               476
55-59               331
60-64               237
65-69               154
10-14               129
70-74               115
75-79                54
80-84                26
90 y más             12
85-89                11
5-9                   1
Name: count, dtype: int64
inculpado_18_años_o_mas
No corresponde    19086
Sí                12135
Sin determinar     5432
Si                 4194
No                 1198
Name: count, dtype: int64

#### Tratamos 'localidad_id'

In [27]:
# Mostrar los valores únicos de las columnas
df_nuevo['localidad_id'].unique()

array(['100', '40', '70', '10', '30', '130', '50', '220', '20', '200',
       '170', '310', '60', '270', '180', '80', '230', '160', '350', '120',
       '110', '105030', '21010', '35020', '210', '90', '21020', '999',
       '140', '260', '150', '450', '390', '400', '250', '190', '240',
       '360', '112020', '35010', '320', '560', '999-999-2', '280', '370',
       '140020', '999-999-6', '290', '300', '28010', '126070', '340',
       '70020', '440', '154040', '77020', '126060', '330', '380', '550',
       '460', '480'], dtype=object)

In [28]:
df_nuevo['localidad_id'].nunique()

62

In [29]:
# Mostrar los valores únicos con su representación exacta
# para ver diferencias entre texto, números, espacios en blanco, etc.
#for x in df_nuevo['localidad_id'].unique():
   # print(repr(x))

In [30]:
# Mostrar las filas donde es igual a, para ver si la info es relevante
print(df_nuevo[df_nuevo['localidad_id'] == '999-999-2'])
print(df_nuevo[df_nuevo['localidad_id'] == '999-999-6'])

       id_hecho  provincia_id                 provincia_nombre localidad_id  \
6515      16185             2  Ciudad Autónoma de Buenos Aires    999-999-2
6516      16185             2  Ciudad Autónoma de Buenos Aires    999-999-2
15934     21996             2  Ciudad Autónoma de Buenos Aires    999-999-2
15935     21996             2  Ciudad Autónoma de Buenos Aires    999-999-2

               localidad_nombre  anio  mes fecha_hecho hora_hecho  \
6515   Localidad sin determinar  2018   11  2018-11-16   21:45:00
6516   Localidad sin determinar  2018   11  2018-11-16   21:45:00
15934  Localidad sin determinar  2020    8  2020-08-15   06:15:00
15935  Localidad sin determinar  2020    8  2020-08-15   06:15:00

        tipo_lugar  ...    victima_sexo victima_identidad_genero  \
6515   Vía pública  ...  No corresponde           No corresponde
6516   Vía pública  ...       Masculino                    Varón
15934  Vía pública  ...  No corresponde           No corresponde
15935  Vía pública  ...       Masculino                    Varón

      victima_identidad_genero_otro victima_tr_edad victima_18_años_o_mas  \
6515                    -----------  No corresponde        No corresponde
6516                No especificado           25-29                    Sí
15934                   -----------  No corresponde        No corresponde
15935               No especificado           15-19                    No

       inculpado_sexo inculpado_identidad_genero  \
6515         Femenino                      Mujer
6516   No corresponde             No corresponde
15934       Masculino                      Varón
15935  No corresponde             No corresponde

      inculpado_identidad_genero_otro inculpado_tr_edad  \
6515                  No especificado             25-29
6516                          -------    No corresponde
15934                 No especificado             20-24
15935                         -------    No corresponde

      inculpado_18_años_o_mas
6515                       Sí
6516           No corresponde
15934                      Sí
15935          No corresponde

[4 rows x 24 columns]
      id_hecho  provincia_id provincia_nombre localidad_id  \
6918     16423             6     Buenos Aires    999-999-6
6919     16423             6     Buenos Aires    999-999-6

              localidad_nombre  anio  mes fecha_hecho hora_hecho  \
6918  Localidad sin determinar  2019    1  2019-01-25   00:30:00
6919  Localidad sin determinar  2019    1  2019-01-25   00:30:00

              tipo_lugar  ...    victima_sexo victima_identidad_genero  \
6918  Cárcel o comisaría  ...  No corresponde           No corresponde
6919  Cárcel o comisaría  ...       Masculino                    Varón

     victima_identidad_genero_otro victima_tr_edad victima_18_años_o_mas  \
6918                   -----------  No corresponde        No corresponde
6919               No especificado           25-29                    Sí

      inculpado_sexo inculpado_identidad_genero  \
6918       Masculino                      Varón
6919  No corresponde             No corresponde

     inculpado_identidad_genero_otro inculpado_tr_edad inculpado_18_años_o_mas
6918                 No especificado    Sin determinar          Sin determinar
6919                         -------    No corresponde          No corresponde

[2 rows x 24 columns]

Se detectaron códigos especiales (999-999-2 y 999-999-6) cuyo contenido en 'localidad_nombre' 
es 'Localidad sin determinar'.
Como el análisis busca mostrar cuáles son las tres provincias y localidades
donde se han detectado la mayor cantidad de homicidios,
se decide reemplazar dichos valores por nulos.

In [31]:
# Reemplazar los códigos de "Localidad sin determinar" por valores nulos (NaN)
df_nuevo['localidad_id'] = df_nuevo['localidad_id'].replace(['999-999-2', '999-999-6'], pd.NA)

In [32]:
# Convertir la columna a tipo numérico (los valores no convertibles quedan como NaN)
df_nuevo['localidad_id'] = pd.to_numeric(df_nuevo['localidad_id'], errors='coerce').astype('Int64')

In [33]:
# Verificar que la conversión se realizó correctamente
df_nuevo['localidad_id'].dtype

Int64Dtype()

In [34]:
df_nuevo['localidad_id'].unique()

<IntegerArray>
[   100,     40,     70,     10,     30,    130,     50,    220,     20,
    200,    170,    310,     60,    270,    180,     80,    230,    160,
    350,    120,    110, 105030,  21010,  35020,    210,     90,  21020,
    999,    140,    260,    150,    450,    390,    400,    250,    190,
    240,    360, 112020,  35010,    320,    560,   <NA>,    280,    370,
 140020,    290,    300,  28010, 126070,    340,  70020,    440, 154040,
  77020, 126060,    330,    380,    550,    460,    480]
Length: 61, dtype: Int64

In [35]:
df_nuevo['localidad_id'].nunique()

60

### Tratamos 'hora_hecho'

In [36]:
df_nuevo['hora_hecho'].value_counts()

hora_hecho
11:11:11    15413
11:11:00      919
00:00:00      665
22:00:00      526
21:00:00      497
            ...
19:09:00        2
09:07:00        2
15:43:00        2
06:19:00        2
16:38:00        2
Name: count, Length: 1152, dtype: int64

In [37]:
from datetime import time
df_nuevo[df_nuevo['hora_hecho'] == time(11,11,11)]

,id_hecho,provincia_id,provincia_nombre,localidad_id,localidad_nombre,anio,mes,fecha_hecho,hora_hecho,tipo_lugar,...,victima_sexo,victima_identidad_genero,victima_identidad_genero_otro,victima_tr_edad,victima_18_años_o_mas,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_años_o_mas
772,12038,82,Santa Fe,270,Rosario,2017,8,2017-08-31,11:11:11,Vía pública,...,No corresponde,No corresponde,-----------,No corresponde,No corresponde,Sin determinar,Sin determinar,No especificado,Sin determinar,Sin determinar
773,12038,82,Santa Fe,270,Rosario,2017,8,2017-08-31,11:11:11,Vía pública,...,Masculino,Varón,No especificado,65-69,Sí,No corresponde,No corresponde,-------,No corresponde,No corresponde
1836,12710,82,Santa Fe,270,Rosario,2018,1,2018-01-28,11:11:11,Domicilio particular,...,No corresponde,No corresponde,-----------,No corresponde,No corresponde,Masculino,Varón,No especificado,35-39,Sí
1837,12710,82,Santa Fe,270,Rosario,2018,1,2018-01-28,11:11:11,Domicilio particular,...,Masculino,Varón,No especificado,85-89,Sí,No corresponde,No corresponde,-------,No corresponde,No corresponde
2221,12955,62,Río Negro,90,Viedma,2017,1,2017-01-01,11:11:11,Vía pública,...,No corresponde,No corresponde,-----------,No corresponde,No corresponde,Masculino,Varón,No especificado,15-19,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38109,37746,6,Buenos Aires,10,Tigre,2024,9,2024-09-28,11:11:11,Vía pública,...,Masculino,Varón,No especificado,30-34,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
38110,37746,6,Buenos Aires,10,Tigre,2024,9,2024-09-28,11:11:11,Vía pública,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Masculino,Varón,No especificado,30-34,Si
38111,37746,6,Buenos Aires,10,Tigre,2024,9,2024-09-28,11:11:11,Vía pública,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Masculino,Varón,No especificado,20-24,Si
38112,37747,6,Buenos Aires,10,Balneario Orense,2024,9,2024-09-04,11:11:11,Vía pública,...,Masculino,Varón,No especificado,25-29,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
38113,37747,6,Buenos Aires,10,Balneario Orense,2024,9,2024-09-04,11:11:11,Vía pública,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Masculino,Varón,No especificado,35-39,Si

In [38]:
df_nuevo[df_nuevo['hora_hecho'] == time(11,11,00)]

,id_hecho,provincia_id,provincia_nombre,localidad_id,localidad_nombre,anio,mes,fecha_hecho,hora_hecho,tipo_lugar,...,victima_sexo,victima_identidad_genero,victima_identidad_genero_otro,victima_tr_edad,victima_18_años_o_mas,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_años_o_mas
29817,30728,58,Neuquén,110,Senillosa,2023,8,2023-08-26,11:11:00,Domicilio particular,...,Masculino,Varón,No especificado,25-29,Sí,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
29818,30728,58,Neuquén,110,Senillosa,2023,8,2023-08-26,11:11:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Masculino,Varón,No especificado,20-24,Sí
30069,30904,82,Santa Fe,270,Rosario,2023,3,2023-03-28,11:11:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Sin determinar,No especificado,Sin determinar,Sí
30070,30904,82,Santa Fe,270,Rosario,2023,3,2023-03-28,11:11:00,Domicilio particular,...,Femenino,Mujer,No especificado,25-29,Sí,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
30305,31052,82,Santa Fe,270,Rosario,2023,7,2023-07-11,11:11:00,Domicilio particular,...,Femenino,Mujer,No especificado,4 o menos,No,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41471,41087,6,Buenos Aires,10,Quilmes,2025,12,2025-12-24,11:11:00,Vía pública,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Masculino,Varón,No especificado,25-29,Si
41479,41090,6,Buenos Aires,10,Quilmes,2025,12,2025-12-30,11:11:00,Vía pública,...,Masculino,Varón,No especificado,15-19,No,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
41480,41090,6,Buenos Aires,10,Quilmes,2025,12,2025-12-30,11:11:00,Vía pública,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Masculino,Varón,No especificado,Sin determinar,Si
41481,41091,6,Buenos Aires,10,Quilmes,2025,12,2025-12-29,11:11:00,Vía pública,...,Masculino,Varón,No especificado,45-49,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
41482,41091,6,Buenos Aires,10,Quilmes,2025,12,2025-12-29,11:11:00,Vía pública,...,No corresponde,No corresponde,No corresponde,No corresponde,No corresponde,Masculino,Varón,No especificado,Sin determinar,Si

Se conservan los datos con horas '11:11:11' y '11:11:00' ya que representan una gran cantidad de registros necesarios para el análisis. Sin embargo a la hora de analizar la hora del suceso, se procederá a tomar dicha hora dentro de una franja horaria más amplia para evitar el impacto que estos valores puedan tener sobre los resultados.

### Tratamos 'victima_18_años_o_mas'

In [39]:
# ver los valores únicos y las veces que aparecen
df_nuevo['victima_18_años_o_mas'].value_counts(dropna=False)

victima_18_años_o_mas
No corresponde    22959
Sí                13939
Si                 3300
No                 1520
Sin determinar      327
Name: count, dtype: int64

In [40]:
# renombramos la columna
df_nuevo = df_nuevo.rename(columns={'victima_18_años_o_mas':'victima_18_anios_o_mas'})

In [41]:
# unificamos la categoría 'Si' para evitar duplicados
df_nuevo['victima_18_anios_o_mas'] = df_nuevo['victima_18_anios_o_mas'].replace('Sí','Si')

In [42]:
df_nuevo['victima_18_anios_o_mas'] = df_nuevo['victima_18_anios_o_mas'].replace('No corresponde', 'Sin determinar')

In [43]:
df_nuevo['victima_18_anios_o_mas'].value_counts()

victima_18_anios_o_mas
Sin determinar    23286
Si                17239
No                 1520
Name: count, dtype: int64

### Tratamos 'victima_identidad_genero_otro'

In [44]:
df_nuevo['victima_identidad_genero_otro'].value_counts(dropna=False)

victima_identidad_genero_otro
No especificado    19086
-----------        16079
No corresponde      6880
Name: count, dtype: int64

In [45]:
df_nuevo['victima_identidad_genero_otro'] = df_nuevo['victima_identidad_genero_otro'].replace(
    '-----------','No especificado')

In [46]:
df_nuevo['victima_identidad_genero_otro'].value_counts()

victima_identidad_genero_otro
No especificado    35165
No corresponde      6880
Name: count, dtype: int64

### Tratamos ''inculpado_identidad_genero_otro'

In [47]:
df_nuevo['inculpado_identidad_genero_otro'].value_counts(dropna=False)

inculpado_identidad_genero_otro
No especificado    28569
-------            13473
Sin determinar         3
Name: count, dtype: int64

In [48]:
df_nuevo['inculpado_identidad_genero_otro'] = df_nuevo['inculpado_identidad_genero_otro'].replace(
    '-------','No especificado')
df_nuevo['inculpado_identidad_genero_otro'] = df_nuevo['inculpado_identidad_genero_otro'].replace(
    'Sin determinar','No especificado')

In [49]:
df_nuevo['inculpado_identidad_genero_otro'].value_counts()

inculpado_identidad_genero_otro
No especificado    42045
Name: count, dtype: int64

### Tratamos 'tipo_lugar_ampliado'

In [50]:
df_nuevo['tipo_lugar_ampliado'].value_counts(dropna=False)

tipo_lugar_ampliado
Vía pública                                            23139
Domicilio particular                                   12222
Sin determinar                                          3207
Comercio                                                 909
Interior de rodados                                      607
Campo/descampado/zona rural                              467
Cárcel o comisaría                                       373
Establecimiento zona rural                               163
Otro lugar                                               146
Río/canal/arroyo/mar/dique                               120
Basural/centro de reciclaje/relleno sanitario             89
Canchas/club                                              84
Bar/ Boliche/Salón de fiestas/Fiesta                      80
Establecimiento de salud                                  77
Hotel/Motel/Hospedaje temporario                          63
Casa/edificio abandonado /Obra en construcción            55
Baldío/terreno/lote                                       54
Predio                                                    53
Barrio de emergencia                                      44
Camping/campamento                                        20
Centro comunitario/centro cultural/asociación civil       16
Bar/Boliche/Salón de fiestas/Fiesta                       14
Establecimiento laboral                                   13
Casa/edificio abandonado/Obra en construcción             12
Geriátrico                                                10
Establecimiento educativo                                  6
Otro                                                       2
Name: count, dtype: int64

In [51]:
df_nuevo['tipo_lugar_ampliado'] = df_nuevo['tipo_lugar_ampliado'].replace(
    'Bar/ Boliche/Salón de fiestas/Fiesta','Bar/Boliche/Salón de fiestas/Fiesta')

In [52]:
df_nuevo['tipo_lugar_ampliado'] = df_nuevo['tipo_lugar_ampliado'].replace(
    'Casa/edificio abandonado /Obra en construcción','Casa/edificio abandonado/Obra en construcción')

In [53]:
df_nuevo['tipo_lugar_ampliado'].value_counts()

tipo_lugar_ampliado
Vía pública                                            23139
Domicilio particular                                   12222
Sin determinar                                          3207
Comercio                                                 909
Interior de rodados                                      607
Campo/descampado/zona rural                              467
Cárcel o comisaría                                       373
Establecimiento zona rural                               163
Otro lugar                                               146
Río/canal/arroyo/mar/dique                               120
Bar/Boliche/Salón de fiestas/Fiesta                       94
Basural/centro de reciclaje/relleno sanitario             89
Canchas/club                                              84
Establecimiento de salud                                  77
Casa/edificio abandonado/Obra en construcción             67
Hotel/Motel/Hospedaje temporario                          63
Baldío/terreno/lote                                       54
Predio                                                    53
Barrio de emergencia                                      44
Camping/campamento                                        20
Centro comunitario/centro cultural/asociación civil       16
Establecimiento laboral                                   13
Geriátrico                                                10
Establecimiento educativo                                  6
Otro                                                       2
Name: count, dtype: int64

## Duplicados

In [54]:
# contar cuántos duplicados hay
df_nuevo.duplicated().sum()

np.int64(1753)

In [56]:
# ver cuáles son
df_nuevo[df_nuevo.duplicated(keep=False)].head()

,id_hecho,provincia_id,provincia_nombre,localidad_id,localidad_nombre,anio,mes,fecha_hecho,hora_hecho,tipo_lugar,...,victima_sexo,victima_identidad_genero,victima_identidad_genero_otro,victima_tr_edad,victima_18_anios_o_mas,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_años_o_mas
1,11535,58,Neuquén,100,Plottier,2017,1,2017-01-14,22:38:00,Domicilio particular,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,Sin determinar,Sin determinar
2,11535,58,Neuquén,100,Plottier,2017,1,2017-01-14,22:38:00,Domicilio particular,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,Sin determinar,Sin determinar
3,11535,58,Neuquén,100,Plottier,2017,1,2017-01-14,22:38:00,Domicilio particular,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,Sin determinar,Sin determinar
46,11573,66,Salta,20,Colonia Santa Rosa,2017,1,2017-01-08,06:30:00,Vía pública,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,20-24,Sí
47,11573,66,Salta,20,Colonia Santa Rosa,2017,1,2017-01-08,06:30:00,Vía pública,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,20-24,Sí

In [57]:
df_nuevo[df_nuevo.duplicated(keep=False)].tail()

,id_hecho,provincia_id,provincia_nombre,localidad_id,localidad_nombre,anio,mes,fecha_hecho,hora_hecho,tipo_lugar,...,victima_sexo,victima_identidad_genero,victima_identidad_genero_otro,victima_tr_edad,victima_18_anios_o_mas,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_años_o_mas
41934,42134,2,Ciudad Autónoma de Buenos Aires,10,Ciudad de Buenos Aires,2024,5,2024-05-06,01:00:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Masculino,Varón,No especificado,65-69,Si
41935,42134,2,Ciudad Autónoma de Buenos Aires,10,Ciudad de Buenos Aires,2024,5,2024-05-06,01:00:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Masculino,Varón,No especificado,65-69,Si
42042,41141,6,Buenos Aires,10,Balneario Orense,2025,6,2025-06-04,17:00:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Sin determinar,NaN,No especificado,Sin determinar,Si
42043,41141,6,Buenos Aires,10,Balneario Orense,2025,6,2025-06-04,17:00:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Sin determinar,NaN,No especificado,Sin determinar,Si
42044,41141,6,Buenos Aires,10,Balneario Orense,2025,6,2025-06-04,17:00:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Sin determinar,NaN,No especificado,Sin determinar,Si

In [58]:
# eliminamos duplicados
df_nuevo = df_nuevo.drop_duplicates()

In [59]:
# confirmar que no queden duplicados
df_nuevo.duplicated().sum()

np.int64(0)

In [60]:
# ver el tamaño final de tabla
print('Cantidad de filas y columnas', df_nuevo.shape)
print('Nombre columnas', df_nuevo.columns)

Cantidad de filas y columnas (40292, 24)
Nombre columnas Index(['id_hecho', 'provincia_id', 'provincia_nombre', 'localidad_id',
       'localidad_nombre', 'anio', 'mes', 'fecha_hecho', 'hora_hecho',
       'tipo_lugar', 'tipo_lugar_otro', 'tipo_lugar_ampliado',
       'motivo_origen_registro', 'motivo_origen_registro_otro', 'victima_sexo',
       'victima_identidad_genero', 'victima_identidad_genero_otro',
       'victima_tr_edad', 'victima_18_anios_o_mas', 'inculpado_sexo',
       'inculpado_identidad_genero', 'inculpado_identidad_genero_otro',
       'inculpado_tr_edad', 'inculpado_18_años_o_mas'],
      dtype='object')

### Tratamos 'victima_tr_edad'

In [61]:
df_nuevo['victima_tr_edad'].value_counts()

victima_tr_edad
No corresponde    21313
20-24              2886
25-29              2759
30-34              2561
15-19              1962
35-39              1799
40-44              1469
45-49              1089
50-54               792
55-59               661
60-64               522
Sin determinar      513
65-69               454
70-74               361
4 o menos           260
75-79               259
10-14               203
80-84               194
5-9                  98
85-89                92
90 y más             45
Name: count, dtype: int64

In [62]:
df_nuevo[df_nuevo['victima_tr_edad'] == 'No corresponde']

,id_hecho,provincia_id,provincia_nombre,localidad_id,localidad_nombre,anio,mes,fecha_hecho,hora_hecho,tipo_lugar,...,victima_sexo,victima_identidad_genero,victima_identidad_genero_otro,victima_tr_edad,victima_18_anios_o_mas,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_años_o_mas
1,11535,58,Neuquén,100,Plottier,2017,1,2017-01-14,22:38:00,Domicilio particular,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,Sin determinar,Sin determinar
4,11536,58,Neuquén,40,Cutral Có,2017,1,2017-01-07,10:35:00,Vía pública,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,20-24,Sí
5,11536,58,Neuquén,40,Cutral Có,2017,1,2017-01-07,10:35:00,Vía pública,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,30-34,Sí
8,11537,58,Neuquén,70,Neuquén,2017,1,2017-01-07,16:38:00,Vía pública,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,25-29,Sí
9,11538,58,Neuquén,10,Barrancas,2017,1,2017-01-02,22:00:00,Domicilio particular,...,No corresponde,No corresponde,No especificado,No corresponde,Sin determinar,Masculino,Varón,No especificado,35-39,Sí
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42038,41032,6,Buenos Aires,40,Necochea - Quequén,2025,4,2025-04-10,16:30:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Sin determinar,NaN,No especificado,Sin determinar,Si
42042,41141,6,Buenos Aires,10,Balneario Orense,2025,6,2025-06-04,17:00:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Sin determinar,NaN,No especificado,Sin determinar,Si
42046,42106,2,Ciudad Autónoma de Buenos Aires,10,Ciudad de Buenos Aires,2024,1,2024-01-20,07:00:00,Otro lugar,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Femenino,Mujer,No especificado,30-34,Si
42048,42142,2,Ciudad Autónoma de Buenos Aires,10,Ciudad de Buenos Aires,2024,4,2024-04-01,03:00:00,Domicilio particular,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Masculino,Varón,No especificado,Sin determinar,Si
42050,42346,10,Catamarca,20,Belén,2025,6,2025-06-29,18:00:00,Otro lugar,...,No corresponde,No corresponde,No corresponde,No corresponde,Sin determinar,Sin determinar,NaN,No especificado,Sin determinar,Si

In [63]:
df_nuevo[df_nuevo['victima_tr_edad'] == 'Sin determinar']

,id_hecho,provincia_id,provincia_nombre,localidad_id,localidad_nombre,anio,mes,fecha_hecho,hora_hecho,tipo_lugar,...,victima_sexo,victima_identidad_genero,victima_identidad_genero_otro,victima_tr_edad,victima_18_anios_o_mas,inculpado_sexo,inculpado_identidad_genero,inculpado_identidad_genero_otro,inculpado_tr_edad,inculpado_18_años_o_mas
58,11578,66,Salta,70,San Ramón de la Nueva Orán (Est. Orán),2017,1,2017-01-25,01:00:00,Vía pública,...,Masculino,Varón,No especificado,Sin determinar,Sin determinar,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
66,11584,26,Chubut,40,Trelew,2017,2,2017-02-24,19:40:00,Domicilio particular,...,Masculino,Varón,No especificado,Sin determinar,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
400,11779,66,Salta,10,El Galpón (Est. Foguista J. F. Juárez),2017,3,2017-03-17,00:00:00,Vía pública,...,Femenino,Mujer,No especificado,Sin determinar,Sin determinar,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
576,11921,58,Neuquén,10,San Martín de los Andes,2017,8,2017-08-04,23:55:00,Domicilio particular,...,Masculino,Varón,No especificado,Sin determinar,Sin determinar,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
892,12191,82,Santa Fe,30,Las Parejas,2017,10,2017-10-20,05:45:00,Domicilio particular,...,Femenino,Mujer,No especificado,Sin determinar,Sin determinar,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41866,41636,2,Ciudad Autónoma de Buenos Aires,10,Ciudad de Buenos Aires,2025,12,2025-12-28,14:00:00,Vía pública,...,Masculino,Varón,No especificado,Sin determinar,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
41948,42141,2,Ciudad Autónoma de Buenos Aires,10,Ciudad de Buenos Aires,2024,12,2024-12-18,05:00:00,Vía pública,...,Masculino,Varón,No especificado,Sin determinar,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
41958,42147,2,Ciudad Autónoma de Buenos Aires,10,Ciudad de Buenos Aires,2024,7,2024-07-05,22:00:00,Vía pública,...,Masculino,Varón,No especificado,Sin determinar,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
41976,42156,2,Ciudad Autónoma de Buenos Aires,10,Ciudad de Buenos Aires,2024,2,2024-02-09,05:00:00,Vía pública,...,Masculino,Varón,No especificado,Sin determinar,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde
42020,42178,2,Ciudad Autónoma de Buenos Aires,10,Ciudad de Buenos Aires,2024,4,2024-04-19,15:00:00,Vía pública,...,Masculino,Varón,No especificado,Sin determinar,Si,No corresponde,No corresponde,No especificado,No corresponde,No corresponde

In [65]:
df_nuevo['victima_tr_edad'] = df_nuevo['victima_tr_edad'].replace('No corresponde', 'Sin determinar')

In [66]:
df_nuevo['victima_tr_edad'].value_counts()

victima_tr_edad
Sin determinar    21826
20-24              2886
25-29              2759
30-34              2561
15-19              1962
35-39              1799
40-44              1469
45-49              1089
50-54               792
55-59               661
60-64               522
65-69               454
70-74               361
4 o menos           260
75-79               259
10-14               203
80-84               194
5-9                  98
85-89                92
90 y más             45
Name: count, dtype: int64

### Tratamos 'inculpado_18_años_o_mas'

In [67]:
# renombramos la columna del inculpado
df_nuevo = df_nuevo.rename(columns={'inculpado_18_años_o_mas':'inculpado_18_anios_o_mas'})

In [68]:
# unificamos la categoría 'Si' y reemplazamos 'No corresponde'
df_nuevo['inculpado_18_anios_o_mas'] = df_nuevo['inculpado_18_anios_o_mas'].replace('Sí', 'Si')
df_nuevo['inculpado_18_anios_o_mas'] = df_nuevo['inculpado_18_anios_o_mas'].replace('No corresponde', 'Sin determinar')

### Tratamos 'inculpado_tr_edad'

In [69]:
# reemplazamos 'No corresponde' en el tramo de edad del inculpado
df_nuevo['inculpado_tr_edad'] = df_nuevo['inculpado_tr_edad'].replace('No corresponde', 'Sin determinar')

In [70]:
df_nuevo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 40292 entries, 0 to 42050
Data columns (total 24 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id_hecho                         40292 non-null  int64
 1   provincia_id                     40292 non-null  int64
 2   provincia_nombre                 40292 non-null  object
 3   localidad_id                     40286 non-null  Int64
 4   localidad_nombre                 40292 non-null  object
 5   anio                             40292 non-null  int64
 6   mes                              40292 non-null  int64
 7   fecha_hecho                      40292 non-null  datetime64[ns]
 8   hora_hecho                       40292 non-null  object
 9   tipo_lugar                       40292 non-null  object
 10  tipo_lugar_otro                  40292 non-null  object
 11  tipo_lugar_ampliado              40292 non-null  object
 12  motivo_origen_registro           40292 non-null  object
 13  motivo_origen_registro_otro      40292 non-null  object
 14  victima_sexo                     40292 non-null  object
 15  victima_identidad_genero         40292 non-null  object
 16  victima_identidad_genero_otro    40292 non-null  object
 17  victima_tr_edad                  40292 non-null  object
 18  victima_18_anios_o_mas           40292 non-null  object
 19  inculpado_sexo                   40292 non-null  object
 20  inculpado_identidad_genero       39936 non-null  object
 21  inculpado_identidad_genero_otro  40292 non-null  object
 22  inculpado_tr_edad                40292 non-null  object
 23  inculpado_18_anios_o_mas         40292 non-null  object
dtypes: Int64(1), datetime64[ns](1), int64(4), object(18)
memory usage: 7.7+ MB

In [71]:
df_nuevo.to_csv('homicidios_limpio.csv', index=False, sep=';', encoding='utf-8')